DROP DATABASE IF EXISTS GEODATA;
CREATE DATABASE GEODATA;
USE GEODATA;

CREATE TABLE PROJECT(
	PROJECT varchar(16) NOT NULL PRIMARY KEY,
	DESCRIPTION varchar(255) NULL
);

drop table if exists LITHOLOGY;
CREATE TABLE LITHOLOGY (
	PROJECT varchar(16) NOT NULL,
	SITE_ID varchar(40) NOT NULL,
	DEPTH_FROM decimal(8, 3) NOT NULL,
	DEPTH_TO decimal(8, 3) NULL,
	LITH varchar(8) NULL,
	LITH_PCT int NULL,
	COLOUR varchar(8) NULL,
	STRUCTURE varchar(8) NULL,
	TEXTURE varchar(8) NULL,
	COMMENT varchar(500) NULL,
	PRIMARY KEY (PROJECT, SITE_ID, depth_FROM)
 );

CREATE TABLE SAMPLE(
	PROJECT varchar(16) NOT NULL,
	SITE_ID varchar(40) NOT NULL,
	SAMPLE_ID varchar(30) NOT NULL,
	DEPTH_FROM decimal(8, 3) NOT NULL,
	DEPTH_TO decimal(8, 3) NOT NULL,
	SAMPLE_TYPE varchar(16) NULL,
	MASS float NULL,
	SAMPLER varchar(32) NULL,
	DATE_SAMPLED DATETIME DEFAULT NOW() NULL,
	PRIMARY KEY (PROJECT, SITE_ID, SAMPLE_ID)
);


CREATE TABLE SITE(
	PROJECT varchar(16) NOT NULL,
	SITE_ID varchar(40) NOT NULL,
	SITE_TYPE varchar(3) NULL,
	START_DEPTH decimal(8, 3) NULL,
	DATE_STARTED DATETIME NULL,
	DATE_COMPLETED DATETIME NULL,
	SITE_PURPOSE varchar(16) NULL,
	SITE_DIAM varchar(16) NULL,
	END_DEPTH decimal(8, 3) NULL,
	COMMENTS varchar(250) NULL,
	GEOLOGIST varchar(32) NULL,
 	PRIMARY KEY (PROJECT, SITE_ID)
);

CREATE TABLE SITE_SURVEY(
	PROJECT varchar(16) NOT NULL,
	SITE_ID varchar(40) NOT NULL,
	INSTANCE smallint NOT NULL,
	DATE_SURVEYED DATETIME NULL,
	COORDSYS varchar(16) NULL,
	EASTING float NULL,
	NORTHING float NULL,
	HEIGHT float NULL,
	PRIMARY KEY (PROJECT, SITE_ID, instance)
);


CREATE TABLE LKP_CATEGORY(
	CATEGORY varchar(16) NOT NULL PRIMARY KEY,
	DESCRIPTION varchar(64) NOT NULL
);


CREATE TABLE LKP_CODE(
	CATEGORY varchar(16) NOT NULL,
	CODE varchar(8) NOT NULL,
	DESCRIPTION varchar(120) NOT NULL,
	PRIMARY KEY (CATEGORY, CODE)
);


CREATE TABLE DESPATCH(
	DESPATCH_ID varchar(16) NOT NULL PRIMARY KEY,
	LAB_ID varchar(20) NOT NULL,
	SEND_DATE DATETIME NOT NULL
);


CREATE TABLE DESPATCH_DETAIL(
	DESPATCH_ID varchar(16) NOT NULL,
	LAB_METHOD varchar(32) NOT NULL,
	ELEMENT varchar(8) NOT NULL,
	UNITS varchar(20) NOT NULL,
 	PRIMARY KEY (DESPATCH_ID,LAB_METHOD,element)
);


CREATE TABLE DESPATCH_SAMPLE(
	DESPATCH_ID varchar(16) NOT NULL,
	SAMPLE_TAG varchar(30) NOT NULL,
	PROJECT varchar(16) NOT NULL,
	SITE_ID varchar(40) NOT NULL,
	SAMPLE_ID varchar(30) NOT NULL,
 	PRIMARY KEY (DESPATCH_ID,SAMPLE_TAG)
);


CREATE TABLE RECEIPT(
	DESPATCH_ID varchar(16) NOT NULL,
	LAB_JOB_NO varchar(16) NOT NULL,
	RECEIPT_DATE DATETIME NOT NULL,
	LAB_DATE DATETIME NULL,
	INPUT_FILE varchar(255) NULL,
	PRIMARY KEY (DESPATCH_ID,LAB_JOB_NO)
); 



CREATE TABLE RESULT(
	DESPATCH_ID varchar(16) NOT NULL,
	LAB_JOB_NO varchar(16) NOT NULL,
	SAMPLE_TAG varchar(30) NOT NULL,
	LAB_METHOD varchar(32) NOT NULL,
	LAB_ELEMENT varchar(8) NOT NULL,
	LAB_UNITS varchar(20) NOT NULL,
	RESULT float NULL,
	RECIEVED_MASS float NULL,
	PRIMARY KEY (DESPATCH_ID,LAB_JOB_NO,SAMPLE_TAG,LAB_METHOD,LAB_ELEMENT)
);


ALTER TABLE LITHOLOGY ADD  CONSTRAINT LITHOLOGY_FK1 FOREIGN KEY(PROJECT, SITE_ID)
REFERENCES SITE (PROJECT, SITE_ID)

ALTER TABLE SAMPLE ADD  CONSTRAINT FK_SAMPLE_SITE FOREIGN KEY(PROJECT, SITE_ID)
REFERENCES SITE (PROJECT, SITE_ID)

ALTER TABLE SITE ADD  CONSTRAINT SITE_FK FOREIGN KEY(PROJECT)
REFERENCES PROJECT (PROJECT)

ALTER TABLE SITE_SURVEY ADD  CONSTRAINT SITE_SURVEY_FK2 FOREIGN KEY(PROJECT, SITE_ID)
REFERENCES SITE (PROJECT, SITE_ID)

ALTER TABLE LKP_CODE ADD  CONSTRAINT FK_LKP_CODE_LKP_CATEGORY FOREIGN KEY(CATEGORY)
REFERENCES LKP_CATEGORY (CATEGORY)

ALTER TABLE DESPATCH_DETAIL ADD  CONSTRAINT DESPATCH_DETAIL_FK1 FOREIGN KEY(DESPATCH_ID)
REFERENCES DESPATCH (DESPATCH_ID)

ALTER TABLE DESPATCH_SAMPLE ADD  CONSTRAINT DESPATCH_SAMPLE_FK1 FOREIGN KEY(DESPATCH_ID)
REFERENCES DESPATCH (DESPATCH_ID)

ALTER TABLE RECEIPT ADD  CONSTRAINT RECEIPT_FK1 FOREIGN KEY(DESPATCH_ID)
REFERENCES DESPATCH (DESPATCH_ID)

ALTER TABLE RESULT ADD  CONSTRAINT RESULT_FK1 FOREIGN KEY(DESPATCH_ID, SAMPLE_TAG)
REFERENCES DESPATCH_SAMPLE (DESPATCH_ID, SAMPLE_TAG)

CREATE INDEX SITE_SK1 ON SITE (PROJECT);
CREATE INDEX SAMPLE_SK1 ON SAMPLE (PROJECT, SITE_ID, DEPTH_FROM, DEPTH_TO);
CREATE INDEX SAMPLE_SK2 ON SAMPLE (PROJECT, SITE_ID);
CREATE INDEX RESULT_SK1 ON RESULT (DESPATCH_ID, SAMPLE_TAG);